version: '3.9'

services:
  app:
    build:
      context: ./backend_app  # Spécifie le chemin vers backend_app
      dockerfile: Dockerfile  # Indique le nom du Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=http://host.docker.internal:54321
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0

